name: Build Windows Executable with Admin

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build .exe with PyInstaller and Admin Manifest
      run: |
        pyinstaller --onefile --name ModifyEdgePolicy --manifest admin.manifest ModifyEdgePolicy.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ModifyEdgePolicy-exe
        path: dist/ModifyEdgePolicy.exe
